# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiycIrZOSa-981ZZG-5931XC1tzKYScY
"""

from google.colab import files
files.upload()

import streamlit as st
import pandas as pd
import json

st.title("Mobile Promoter Dashboard")

uploaded_file = st.file_uploader("Upload a JSON file", type=["json"])
if uploaded_file is not None:
    data = json.load(uploaded_file)
    st.json(data)  # Display the JSON

import streamlit as st
import pandas as pd
import json

st.set_page_config(page_title="Mobile Promoter Dashboard", layout="wide")

st.title("📱 Mobile Promoter Dashboard")

uploaded_file = st.file_uploader("Upload a JSON file", type=["json"])

if uploaded_file:
    try:
        data = json.load(uploaded_file)
        df = pd.DataFrame(data)

        st.subheader("Data Preview")
        st.dataframe(df)

        st.subheader("Brand-wise Count")
        if 'brand' in df.columns:
            st.bar_chart(df['brand'].value_counts())
        else:
            st.warning("Column 'brand' not found in uploaded file.")

    except Exception as e:
        st.error(f"Error loading file: {e}")
else:
    st.info("Please upload a JSON file to begin.")